version: "3.8"

services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    ports:
      - "8888:8888/tcp"
      - "8888:8888/udp"
    volumes:
      - ./vpn/data:/gluetun
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./sonarr/config:/config
      - ./series:/series
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./radarr/config:/config
      - ./movies:/movies
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./jellyfin/config:/config
      - ./media:/media
      - ./series:/series
      - ./movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    restart: unless-stopped